### ISSUE TITLE
cc: error: unrecognized command line option '-Wc ++ 11-compat-deprecated-writable-strings'

### ISSUE THREAD

**Issue by ljmediavilla** [jjustman/libatsc3#118]
this weekend I wanted to try the libatsc3 library, for which I wanted to install it for the first time on an Ubuntu 18.04.5 LTS machine, I followed the steps that you detail in your blog, in the SRT + STLTP article: ATSC 3.0 Virtual Demod and ROUTE object extraction for remote market deployment testing, the steps I followed were the following:

git clone https://github.com/jjustman/libatsc3.git

cd libatsc3

# (first time) install required toolchain for compilation
./linux-build

# (first time) build bento4 library
cd src
./build_linux.sh

# build libatsc3 and tools
make

As you specify, but in step
./build_linux.sh
I get the following error
cc -Wno-nullability-completeness -Wno-expansion-to-defined -Wno-builtin-requires-header -Wno-c ++ 11-extensions -Wc ++ 11-compat-deprecated-writable-strings -Wno-writable- strings -g -c atsc3_lls.c
cc: error: unrecognized command line option '-Wc ++ 11-compat-deprecated-writable-strings'
makefile: 338: Failed instructions for target 'atsc3_lls.o'
make: *** [atsc3_lls.o] Error 1
![Captura de pantalla de 2021-03-14 12-35-38](https://user-images.githubusercontent.com/71518845/111078701-d102a500-84c4-11eb-9121-ed9b05890d43.png)

I hope and you can help me with your experience and knowledge, I thank you in advance

**Comment by jjustman** [comment]
For SRT, please force a git reset via:

cd srt
git reset --hard

and try rebuilding
