### ISSUE TITLE
no credential issue

### ISSUE THREAD

**Issue by sangyoun-han** [jjustman/libatsc3#120]
I am new to libatsc3 
when compiling android in tht android studio, I got the belowe build issuue.
<error log>
Could not determine the dependencies of task ':atsc3_bridge:lint'.
> Could not resolve all dependencies for configuration ':atsc3_bridge:releaseRuntimeClasspath'.
   > You cannot configure authentication schemes for this repository type if no credentials are provided.

Can you help me to solve it?

**Comment by sangyoun-han** [comment]
I am new to libatsc3
when compiling android in tht android studio, I got the belowe build issuue.

Could not determine the dependencies of task ':atsc3_bridge:lint'.

Could not resolve all dependencies for configuration ':atsc3_bridge:releaseRuntimeClasspath'.
You cannot configure authentication schemes for this repository type if no credentials are provided.

Can you help me to solve it?

**Comment by jjustman** [comment]
Yes, please make sure that "use_local_src_libatsc3_folder is set to true in gradle.properties, otherwise, it will try to pull down pre-built artifacts from a non-public artifact server, see the following in build.gradle:

 if (!project.getProperty('org.gradle.project.use_local_src_libatsc3_folder').toBoolean()) {

            maven {
                url 'https://pkgs.dev.azure.com/NGWP/Middleware/_packaging/middleware/maven/v1'
                name 'middleware'
                authentication {
                    basic(BasicAuthentication)
                }
            }
        } else {
            mavenCentral()
        }
