### ISSUE TITLE
Failure to clone airwavz_redzone_sdk

### ISSUE THREAD

**Issue by WizzerWorks** [jjustman/libatsc3#124]
Attempted to clone libatsc3 with:

````
git clone --branch develop --recurse-submodules https://github.com/jjustman/libatsc3.git
````
airwavz_redzone_sdk submodule failed with:

Cloning into '/media/workarea/msm/Projects/libatsc3/airwavz_redzone_sdk'...
Username for 'https://dev.azure.com': 
Password for 'https://dev.azure.com': 
fatal: Authentication failed for 'https://dev.azure.com/NGWP/Middleware/_git/airwavz_redzone_sdk/'
fatal: clone of 'https://dev.azure.com/NGWP/Middleware/_git/airwavz_redzone_sdk' into submodule path '/media/workarea/msm/Projects/libatsc3/airwavz_redzone_sdk' failed
Failed to clone 'airwavz_redzone_sdk' a second time, aborting

**Comment by jjustman** [comment]
No, but unfortunately there is no way to specify submodules in git as optional.

I may move/remove these private repos to another git submodule to avoid them being a blocker for non-proprietary checkouts.

**Comment by jjustman** [comment]
Airwavz SDK-v2 can be downloaded from here:

https://redzonereceiver.tv/product/redzone-receiver-plus
