### ISSUE TITLE
Is there a clearer file available about  "lib atsc3 core event flow with callbacks - jjustman.pdf"

### ISSUE THREAD

**Issue by derekcmini** [jjustman/libatsc3#35]
Is there a clearer file available?  (in the architecture folder: 2019-08-11 - lib atsc3 core event flow with callbacks - jjustman.pdf,  can't see clearly)

Thank you for your contribution to this project.

**Comment by derekcmini** [comment]
Re-state my earily question: would you please provide a better resoluation version of the file "**lib atsc3 core event flow with callbacks - jjustman.pdf**" ?

**Comment by jjustman** [comment]
Marking as dup #37
