### ISSUE TITLE
would you please provide a better resoluation version of the file

### ISSUE THREAD

**Issue by derekcmini** [jjustman/libatsc3#37]
Re-state my earily question: would you please provide a better resoluation version of the file "lib atsc3 core event flow with callbacks - jjustman.pdf" ?

**Comment by jjustman** [comment]
Derek,

Can you try with a different PDF viewer, it should be a vector sequence diagram and able to zoom in to any level of detail.

I also have updates with the latest working branch I need to put in over the next few days for event callbacks, but this version should cover the spirit of the design.

Thanks
J


-------- Original message --------

**Comment by jjustman** [comment]
Derek,

I've made some additional updates to the sequence diagram with the new event callback flows, can you please check out the following PDF in Chrome and see if you are still having low-resolution issues?

https://github.com/jjustman/libatsc3/blob/mfu_ooo_context_callback_lls/architecture/2019-10-25%20-%20libatsc3%20core%20event%20flow%20with%20callbacks%20-%20MMT%20MFU%20-%20jjustman.pdf

Best,
J

**Comment by derekcmini** [comment]
That looks very clear, thank you for the file provided.
