### ISSUE TITLE
How to use the tcpreplay to play a PCAP file ?

### ISSUE THREAD

**Issue by yc0815** [jjustman/libatsc3#38]
Dear jjustman,
 Thank you very much for providing this ATSC3.0 code and teaching.  Some basic questions would like to benefit from you.
  1. What is command for tcpreplay to paly the PCAP sample file ?
  2. Do I need two Network interfaces to run the tcpreplay in my ubuntu linux VM ?

**Comment by jjustman** [comment]
YC,

In order to play back pcap samples, I recommend the following to stream on lo (loopback i/f):

# in a separate terminal window
sudo su
while : do
tcpreplay -i lo pcap_file_name_here

# to run playback, after a successful make:
cd tools
sudo su
./atsc3_listener_metrics_ncurses_httpd_isobmff lo

note: please make sure ffplay binary is in the tools/ directory, as it's not yet part of the build chain.

**Comment by yc0815** [comment]
justman,
Thanks a lot !  It was worked!  

I downloaded the master branch codes on a clean Linux VM (ubuntu 18.04 LTS/VirtualBox), and followed your suggestions.

I  use command apt-get install ffmpeg  and copied the ffplay binary (/usr/bin/ffplay) to the src/tools

My network interface is enp0s17.
 
I open a terminal window  and run the command :

tcpreplay -i  enp0s17 -l0 -K -M10   2019-05-07-4mmt-720p-647mhz-good.pcap

open an another  terminal window  run the command :
sudo ./metrics_ncurses_httpd_isobmff  enp0s17
press the button 'm'  and  then press 's'  to set  the service id  16.
press the 'p '  to play the video
The ffplay pipe window  was running.  

There are two small questions: 
1. Are my tcpreplay parameters correct ?
2. How to use the ffplay cache:http:127.0.0.1/video.m4s  to play the video? (I tried and it was hanged)

**Comment by jjustman** [comment]
your tcpreplay parameters can be much simpler, I commonly only use tcpreplay -i vnic0 pcap_file_name with no issues.

For playing via ffplay, recent changes in the ROUTE handling will require you to play it from the tools folder in the route/service_id/manifest.mpd file, where service_id is the ALC service id of the emission.  I recommend GPAC for playing back ROUTE/DASH locally.
