### ISSUE TITLE
can I use the ATSC3.0 tuner to receive the RF (from Dectec)with use the libatsc3 project to play video

### ISSUE THREAD

**Issue by derekcmini** [jjustman/libatsc3#41]
I  am plan to purchase 
**ATSC3.0 tuner** (https://redzonereceiver.tv/product/redzone-receiver-kit)
**ATSC3.0 TX** (https://www.dektec.com/products/USB/DTU-315/)
and use  ATSC3.0 content source (pcap file) and this project **libatsc3**

But, I don't konw how to use tuner with libatsc3 to play video, 
Can you teach me about the operation of libatsc3?

**Comment by jjustman** [comment]
Hi, 

Just a quick update - ATSC 3.0 modulation can be performed on the DekTek (with the GOLD option for ATSC 3.0 modulation), with an IP-based flow pcap using https://github.com/jjustman/dektec_atsc3_tools

I am working to add in STLTP input support for the dektek_atsc3_tools as an A/324 standard input source.

In regards to the RedZone receiver, I have been working with the Airwavz team to provide an open-source SDK PHY implementation, and this should be integrated into the libatsc3 Android sample app in the next few weeks.

Best,
J

**Comment by rima228** [comment]
Hi,
Can I use DTU-315 and your GitHub project https://github.com/jjustman/dektec_atsc3_tools to play a pcap file? If so can you please help out on how to do that.

Thanks

**Comment by jjustman** [comment]
The Airwavz Redzone V2 SDK can be downloaded here, and should be able to be compiled into libatsc3:

https://redzonereceiver.tv/product/redzone-receiver-plus

be sure to set phy_airwavz_enabled=true in gradle.properties:

# note: jjustman-2020-12-22 - requires V2 Airwavz Redzone Receiver SDK - not included
org.gradle.project.phy_airwavz_enabled=false
