### ISSUE TITLE
Issue while compiling the project 

### ISSUE THREAD

**Issue by samvaid** [jjustman/libatsc3#47]
I am having issue in compiling the libatsc3 project. The atsc3_listner_metrics_ncurses_httpd_isobmff file is not available in the github folder. Also while compiling the source code I keep getting the error “recipe for target ‘libatsc3_bento4_gpl.o’ failed.

**Comment by jjustman** [comment]
atsc3_listner_metrics_ncurses_httpd_isobmff would be the resulting compilation output.

Can you please run in the src folder the build_linux.sh script to build the bento4 GPL library set and then re-run make?

**Comment by jjustman** [comment]
Closing, please re-open if you are unable to run the dockerized bento4 build script for GPL-cross complied usage
