### ISSUE TITLE
Does libatsc3 support direct dash playback? 

### ISSUE THREAD

**Issue by derekcmini** [jjustman/libatsc3#48]
Does libatsc3 support direct dash playback? 
Is it allowed to open the browser on the local terminal, access the local http://127.0.0.1/xxxx.mpd, and play the video.

**Comment by jjustman** [comment]
A quick work-around is to use python3 to host a http server from your cwd, ala:

python3 -m http.server

otherwise, GPAC (mp4client) should be able to play back the local stream while libatsc3 is running (i.e. we patch the availabilityStartTime value to be time(&now)

**Comment by jjustman** [comment]
Also, the android sample app will perform DASH playback when using a PCAP file (e.g. ip-multicast pre-ALP encapsulation)
