### ISSUE TITLE
How to get the MPD content?

### ISSUE THREAD

**Issue by derekcmini** [jjustman/libatsc3#49]
How to get the MPD content related to the currently selected service ID?

**Comment by jjustman** [comment]
The easiest way to accomplish this task is by running the following in src/tools:

/atsc3_alc_listener_mde_writer vnic1 s 5007

(where 5007 is the service_id to capture)

the ALC payloads will be written out to route/5007/ ala:

jjustman@sdg-komo-mac188 5007 % ls -l
total 9472
-rw-r--r--  1 jjustman  932231305   12440 Mar 26 00:00 a2_2-1583606265.m4s
-rw-r--r--  1 jjustman  932231305   12440 Mar 26 00:00 a2_2-1583606266.m4s
-rw-r--r--  1 jjustman  932231305   12440 Mar 26 00:00 a2_2-1583606267.m4s
-rw-r--r--  1 jjustman  932231305   12440 Mar 26 00:00 a2_2-1583606268.m4s
-rw-r--r--  1 jjustman  932231305   12440 Mar 26 00:00 a2_2-1583606269.m4s
-rw-r--r--  1 jjustman  932231305   12440 Mar 26 00:00 a2_2-1583606270.m4s
-rw-r--r--  1 jjustman  932231305     622 Mar 26 00:00 a2_2-init.mp4
-rw-r--r--  1 jjustman  932231305    1146 Mar 26 00:00 d3_3-1583606264.m4s
-rw-r--r--  1 jjustman  932231305    1146 Mar 26 00:00 d3_3-1583606265.m4s
-rw-r--r--  1 jjustman  932231305    1146 Mar 26 00:00 d3_3-1583606266.m4s
-rw-r--r--  1 jjustman  932231305    1146 Mar 26 00:00 d3_3-1583606267.m4s
-rw-r--r--  1 jjustman  932231305    1146 Mar 26 00:00 d3_3-1583606268.m4s
-rw-r--r--  1 jjustman  932231305    1146 Mar 26 00:00 d3_3-1583606269.m4s
-rw-r--r--  1 jjustman  932231305    1146 Mar 26 00:00 d3_3-1583606270.m4s
-rw-r--r--  1 jjustman  932231305     613 Mar 26 00:00 d3_3-init.mp4
-rw-r--r--  1 jjustman  932231305     391 Mar 26 00:00 envelope.xml
-rw-r--r--  1 jjustman  932231305    2510 Mar 26 00:00 mpd.mpd
-rw-r--r--  1 jjustman  932231305    2159 Mar 26 00:00 stsid.sls
-rw-r--r--  1 jjustman  932231305     514 Mar 26 00:00 usbd.rusd
-rw-r--r--  1 jjustman  932231305  778840 Mar 26 00:00 video-1583606265.mp4v
-rw-r--r--  1 jjustman  932231305  784415 Mar 26 00:00 video-1583606266.mp4v
-rw-r--r--  1 jjustman  932231305  781802 Mar 26 00:00 video-1583606267.mp4v
-rw-r--r--  1 jjustman  932231305  793916 Mar 26 00:00 video-1583606268.mp4v
-rw-r--r--  1 jjustman  932231305  770015 Mar 26 00:00 video-1583606269.mp4v
-rw-r--r--  1 jjustman  932231305  776771 Mar 26 00:00 video-1583606270.mp4v
-rw-r--r--  1 jjustman  932231305     785 Mar 26 00:00 video-init.mp4v

This change was added in pull #52
