### ISSUE TITLE
Building and testing the Android sample app

### ISSUE THREAD

**Issue by yanger1975** [jjustman/libatsc3#55]
Hi jjustman,

We tried to build and test the Android sample app. 
1. When we tried to build the app, there was a issue about missing "ListenPLP1" method, which was used in src/atsc3_phy_mmt_player_bridge.cpp. We thought that depended on some physical device, so we mark the line and the APK can be generated.

2. When we tested the APK and open a pcap file, we saw the PcapThreadParser was pushing the packet, but the player didn't show when clicking [PLAY]. The screenshot can be referred to https://imgur.com/fpN9rmQ   

Could you please tell us what would be the issue?

**Comment by jjustman** [comment]
Hi,

After reviewing your screenshot, it looks like the pcap you are trying to play back is either STLTP or does not contain LLS (224.0.23.60:4937).

Can you please provide the pcap you used for testing?

Regarding #1 - this should be fixed in the * route-dash-alc-multiple-object-same-content-type branch, and will be merging to master in the next week or so.

J

**Comment by yanger1975** [comment]
We used the pcap files from https://github.com/jjustman/atsc-3.0-mmt-pcaps
2019-12-05-stltp-dallas/dallas-stltp-12-05-07-04-1575547471.pcap
2019-12-05-stltp-lab-digicap/lab-digicap-stltp-12-05-07-34-1575549244.pcap

So what are the limiations of pcap files?

**Comment by jjustman** [comment]
The STLTP muxes aren't yet supported in the android client.  

You will need to run them thru a demux using https://github.com/jjustman/libatsc3/blob/master/src/listener_tests/atsc3_stltp_listener_alp_reflector.cpp

e.g. (239.x.x.x is the stltp)

1.) ./atsc3_stltp_alp_listener_reflector_test eth0 239.x.x.x 30000 lo 0 > /dev/
null &

2.) tcpreplay -i eth0 input_stltp_file.pcap

3.) tcpdump -i lo -s 65535 -w demux.pcap

and then you can play back the demux.pcap file in the android sample app

**Comment by yanger1975** [comment]
Thanks for your help. We have seen the content in ExoPlayer.
