### ISSUE TITLE
FFplay does not open when running atsc3_listener_metrics_ncurses_httpd_isobmff

### ISSUE THREAD

**Issue by elrevi** [jjustman/libatsc3#56]
Hi jjustman,

We are trying to play back one of your PCAP files (2019-05-07-4mmt-720p-647mhz-good.pcap) using tcpreplay and atsc3_listener_metrics_ncurses_httpd_isobmff. It all works fine, but when we press 'p' to play the video nothing happens. We have copied the ffplay binary to the src/tools folder, as recommended, but it doesn't seem to work.

Did we miss something?

**Comment by yanger1975** [comment]
@elrevi  
In atsc3_listener_metrics_ncurses_httpd_isobmff screen, did you press [m] to switch to MMT mode, and press [s] to input a service id, then press [p]?

**Comment by elrevi** [comment]
Hi @yanger1975, thanks for your reply. 

We press 'm' to switch to MMT mode, then we press 's' to select the service and 'p' to start the playback. After that, we can see the message 'MMT: Starting playback for service_id: 16, video packet_id: 1, audio packet_id: 2', as you can see in the picture, but the video is never displayed.

![imagen](https://user-images.githubusercontent.com/26821108/86440446-c0314b00-bd0a-11ea-9be9-92b59b4e2188.png)

**Comment by yanger1975** [comment]
![image](https://user-images.githubusercontent.com/6315687/86446937-32c01c00-bd47-11ea-8e5d-b08533816046.png)
![Screenshot from 2020-07-03 16-00-16](https://user-images.githubusercontent.com/6315687/86447103-6bf88c00-bd47-11ea-81b5-b0a252372c55.jpg)

Hi @elrevi ,
Please check the screenshot. It is ok in my side.

And checked with your question, you said "We have copied the ffplay binary to the src/tools folder." 
 
The correct way is that you should copy or link ffplay to "the same folder of atsc3_listener_metrics_ncurses_httpd_isobmff."   And then run atsc3_listener_metrics_ncurses_httpd_isobmff in the folder.  You can try again and check.

**Comment by elrevi** [comment]
Hi @yanger1975, you are right. 
However, in this case, atsc3_listener_metrics_ncurses_httpd_isobmff is inside the src/tools folder, as you can see in the picture.

![imagen](https://user-images.githubusercontent.com/26821108/86455427-e3ff8b80-bd20-11ea-940d-d5d291bf302a.png)
